version: 0.1
            
phases:

  install: 
    commands:
      - go get -u github.com/golang/lint/golint
      - echo Build started on `date`
      - echo Compiling the Python code...
  pre_build: 
    commands:

      # Ensure code passes all lint tests
      - golint -set_exit_status

      # Run all tests included with our application
      - go test
      - python test_primes.py

  build:
    commands:

      # Build our application
      - go build -o app

artifacts:
  files:
    - app
    - appspec.yml
    - buildspec.yml
    - config/*
    - codedeploy/*
    - cloudformation/*
